package hr.optimit.hibernate.model;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

// TODO: Auto-generated Javadoc
/**
 * ApnaUser generated by hbm2java.
 */
@Entity
@Table(name = "APNA_USER", uniqueConstraints = @UniqueConstraint(columnNames = "USER_USERNAME") )
public class ApnaUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** The user id. */
	private Long userId;
	
	/** The user username. */
	private String userUsername;
	
	/** The user password. */
	private String userPassword;
	
	/** The user status. */
	private String userStatus;
	
	/** The user role. */
	private String userRole;
	
	/** The user first name. */
	private String userFirstName;
	
	/** The user last name. */
	private String userLastName;
	
	/** The user email. */
	private String userEmail;
	
	/** The user creation timestamp. */
	private Timestamp userCreationTimestamp;
	
	/** The sys modification timestamp. */
	private Timestamp sysModificationTimestamp;
	
	/** The sys modification user. */
	private Long sysModificationUser;
	
	/** The allowed domains. */
	private String allowedDomains;

	/**
	 * Instantiates a new apna user.
	 */
	public ApnaUser() {
	}

	/**
	 * Instantiates a new apna user.
	 *
	 * @param userId the user id
	 * @param userUsername the user username
	 * @param userPassword the user password
	 * @param userStatus the user status
	 * @param userRole the user role
	 * @param userFirstName the user first name
	 * @param userLastName the user last name
	 * @param userCreationTimestamp the user creation timestamp
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 * @param allowedDomains the allowed domains
	 */
	public ApnaUser(Long userId, String userUsername, String userPassword, String userStatus, String userRole,
			String userFirstName, String userLastName, Timestamp userCreationTimestamp,
			Timestamp sysModificationTimestamp, Long sysModificationUser, String allowedDomains) {
		this.userId = userId;
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userStatus = userStatus;
		this.userRole = userRole;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userCreationTimestamp = userCreationTimestamp;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
		this.allowedDomains = allowedDomains;
	}

	/**
	 * Instantiates a new apna user.
	 *
	 * @param userId the user id
	 * @param userUsername the user username
	 * @param userPassword the user password
	 * @param userStatus the user status
	 * @param userRole the user role
	 * @param userFirstName the user first name
	 * @param userLastName the user last name
	 * @param userEmail the user email
	 * @param userCreationTimestamp the user creation timestamp
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 * @param allowedDomains the allowed domains
	 */
	public ApnaUser(Long userId, String userUsername, String userPassword, String userStatus, String userRole,
			String userFirstName, String userLastName, String userEmail, Timestamp userCreationTimestamp,
			Timestamp sysModificationTimestamp, Long sysModificationUser, String allowedDomains) {
		this.userId = userId;
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userStatus = userStatus;
		this.userRole = userRole;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmail = userEmail;
		this.userCreationTimestamp = userCreationTimestamp;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
		this.allowedDomains = allowedDomains;
	}

	/**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
	@Id
	@Column(name = "USER_ID", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * Sets the user id.
	 *
	 * @param userId the new user id
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * Gets the user username.
	 *
	 * @return the user username
	 */
	@Column(name = "USER_USERNAME", unique = true, nullable = false, length = 20)
	public String getUserUsername() {
		return this.userUsername;
	}

	/**
	 * Sets the user username.
	 *
	 * @param userUsername the new user username
	 */
	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	/**
	 * Gets the user password.
	 *
	 * @return the user password
	 */
	@Column(name = "USER_PASSWORD", nullable = false, length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	/**
	 * Sets the user password.
	 *
	 * @param userPassword the new user password
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * Gets the user status.
	 *
	 * @return the user status
	 */
	@Column(name = "USER_STATUS", nullable = false, length = 20)
	public String getUserStatus() {
		return this.userStatus;
	}

	/**
	 * Sets the user status.
	 *
	 * @param userStatus the new user status
	 */
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * Gets the user role.
	 *
	 * @return the user role
	 */
	@Column(name = "USER_ROLE", nullable = false, length = 20)
	public String getUserRole() {
		return this.userRole;
	}

	/**
	 * Sets the user role.
	 *
	 * @param userRole the new user role
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	/**
	 * Gets the user first name.
	 *
	 * @return the user first name
	 */
	@Column(name = "USER_FIRST_NAME", nullable = false, length = 30)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	/**
	 * Sets the user first name.
	 *
	 * @param userFirstName the new user first name
	 */
	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	/**
	 * Gets the user last name.
	 *
	 * @return the user last name
	 */
	@Column(name = "USER_LAST_NAME", nullable = false, length = 30)
	public String getUserLastName() {
		return this.userLastName;
	}

	/**
	 * Sets the user last name.
	 *
	 * @param userLastName the new user last name
	 */
	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	/**
	 * Gets the user email.
	 *
	 * @return the user email
	 */
	@Column(name = "USER_EMAIL", length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	/**
	 * Sets the user email.
	 *
	 * @param userEmail the new user email
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * Gets the user creation timestamp.
	 *
	 * @return the user creation timestamp
	 */
	@Column(name = "USER_CREATION_TIMESTAMP", nullable = false)
	public Timestamp getUserCreationTimestamp() {
		return this.userCreationTimestamp;
	}

	/**
	 * Sets the user creation timestamp.
	 *
	 * @param userCreationTimestamp the new user creation timestamp
	 */
	public void setUserCreationTimestamp(Timestamp userCreationTimestamp) {
		this.userCreationTimestamp = userCreationTimestamp;
	}

	/**
	 * Gets the sys modification timestamp.
	 *
	 * @return the sys modification timestamp
	 */
	@Column(name = "SYS_MODIFICATION_TIMESTAMP", nullable = false)
	public Timestamp getSysModificationTimestamp() {
		return this.sysModificationTimestamp;
	}

	/**
	 * Sets the sys modification timestamp.
	 *
	 * @param sysModificationTimestamp the new sys modification timestamp
	 */
	public void setSysModificationTimestamp(Timestamp sysModificationTimestamp) {
		this.sysModificationTimestamp = sysModificationTimestamp;
	}

	/**
	 * Gets the sys modification user.
	 *
	 * @return the sys modification user
	 */
	@Column(name = "SYS_MODIFICATION_USER", nullable = false)
	public Long getSysModificationUser() {
		return this.sysModificationUser;
	}

	/**
	 * Sets the sys modification user.
	 *
	 * @param sysModificationUser the new sys modification user
	 */
	public void setSysModificationUser(Long sysModificationUser) {
		this.sysModificationUser = sysModificationUser;
	}

	/**
	 * Gets the allowed domains.
	 *
	 * @return the allowed domains
	 */
	@Column(name = "ALLOWED_DOMAINS", nullable = false, length = 50)
	public String getAllowedDomains() {
		return this.allowedDomains;
	}

	/**
	 * Sets the allowed domains.
	 *
	 * @param allowedDomains the new allowed domains
	 */
	public void setAllowedDomains(String allowedDomains) {
		this.allowedDomains = allowedDomains;
	}
	
}
