package hr.optimit.hibernate.model;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

// TODO: Auto-generated Javadoc
/**
 * UtActivity generated by hbm2java.
 */
@Entity
@Table(name = "UT_ACTIVITY")
public class UtActivity implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The activity id. */
	private Long activityId;
	
	/** The ut task. */
	private UtTask utTask;
	
	/** The ut location. */
	private UtLocation utLocation;
	
	/** The activity description. */
	private String activityDescription;
	
	/** The activity ref. */
	private String activityRef;
	
	/** The activity start date. */
	private Date activityStartDate;
	
	/** The activity end date. */
	private Date activityEndDate;
	
	/** The activity billable. */
	private Boolean activityBillable;
	
	/** The activity user id. */
	private ApnaUser activityUser;
	
	/** The sys modification timestamp. */
	private Timestamp sysModificationTimestamp;
	
	private ApnaUser sysModificationUser;

	/**
	 * Instantiates a new ut activity.
	 */
	public UtActivity() {
	}

	/**
	 * Instantiates a new ut activity.
	 *
	 * @param activityId the activity id
	 * @param utTask the ut task
	 * @param utLocation the ut location
	 * @param activityStartDate the activity start date
	 * @param activityEndDate the activity end date
	 * @param activityBillable the activity billable
	 * @param activityUser the activity user
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 */
	public UtActivity(Long activityId, UtTask utTask, UtLocation utLocation, Date activityStartDate,
			Date activityEndDate, Boolean activityBillable, ApnaUser activityUser,
			Timestamp sysModificationTimestamp, ApnaUser sysModificationUser) {
		this.activityId = activityId;
		this.utTask = utTask;
		this.utLocation = utLocation;
		this.activityStartDate = activityStartDate;
		this.activityEndDate = activityEndDate;
		this.activityBillable = activityBillable;
		this.activityUser = activityUser;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
	}

	/**
	 * Instantiates a new ut activity.
	 *
	 * @param activityId the activity id
	 * @param utTask the ut task
	 * @param utLocation the ut location
	 * @param activityDescription the activity description
	 * @param activityRef the activity ref
	 * @param activityStartDate the activity start date
	 * @param activityEndDate the activity end date
	 * @param activityBillable the activity billable
	 * @param activityUser the activity user
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 */
	public UtActivity(Long activityId, UtTask utTask, UtLocation utLocation, String activityDescription,
			String activityRef, Date activityStartDate, Date activityEndDate, Boolean activityBillable,
			ApnaUser activityUser, Timestamp sysModificationTimestamp, ApnaUser sysModificationUser) {
		this.activityId = activityId;
		this.utTask = utTask;
		this.utLocation = utLocation;
		this.activityDescription = activityDescription;
		this.activityRef = activityRef;
		this.activityStartDate = activityStartDate;
		this.activityEndDate = activityEndDate;
		this.activityBillable = activityBillable;
		this.activityUser = activityUser;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
	}

	/**
	 * Gets the activity id.
	 *
	 * @return the activity id
	 */
	@Id
	@Column(name = "ACTIVITY_ID", unique = true, nullable = false)
	public Long getActivityId() {
		return this.activityId;
	}

	/**
	 * Sets the activity id.
	 *
	 * @param activityId the new activity id
	 */
	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

	/**
	 * Gets the ut task.
	 *
	 * @return the ut task
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTIVITY_TASK_ID", nullable = false)
	public UtTask getUtTask() {
		return this.utTask;
	}

	/**
	 * Sets the ut task.
	 *
	 * @param utTask the new ut task
	 */
	public void setUtTask(UtTask utTask) {
		this.utTask = utTask;
	}

	/**
	 * Gets the ut location.
	 *
	 * @return the ut location
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTIVITY_LOCATION_ID", nullable = false)
	public UtLocation getUtLocation() {
		return this.utLocation;
	}

	/**
	 * Sets the ut location.
	 *
	 * @param utLocation the new ut location
	 */
	public void setUtLocation(UtLocation utLocation) {
		this.utLocation = utLocation;
	}

	/**
	 * Gets the activity description.
	 *
	 * @return the activity description
	 */
	@Column(name = "ACTIVITY_DESCRIPTION", length = 2000)
	public String getActivityDescription() {
		return this.activityDescription;
	}

	/**
	 * Sets the activity description.
	 *
	 * @param activityDescription the new activity description
	 */
	public void setActivityDescription(String activityDescription) {
		this.activityDescription = activityDescription;
	}

	/**
	 * Gets the activity ref.
	 *
	 * @return the activity ref
	 */
	@Column(name = "ACTIVITY_REF", length = 20)
	public String getActivityRef() {
		return this.activityRef;
	}

	/**
	 * Sets the activity ref.
	 *
	 * @param activityRef the new activity ref
	 */
	public void setActivityRef(String activityRef) {
		this.activityRef = activityRef;
	}

	/**
	 * Gets the activity start date.
	 *
	 * @return the activity start date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "ACTIVITY_START_DATE", nullable = false, length = 7)
	public Date getActivityStartDate() {
		return this.activityStartDate;
	}

	/**
	 * Sets the activity start date.
	 *
	 * @param activityStartDate the new activity start date
	 */
	public void setActivityStartDate(Date activityStartDate) {
		this.activityStartDate = activityStartDate;
	}

	/**
	 * Gets the activity end date.
	 *
	 * @return the activity end date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "ACTIVITY_END_DATE", nullable = false, length = 7)
	public Date getActivityEndDate() {
		return this.activityEndDate;
	}

	/**
	 * Sets the activity end date.
	 *
	 * @param activityEndDate the new activity end date
	 */
	public void setActivityEndDate(Date activityEndDate) {
		this.activityEndDate = activityEndDate;
	}

	/**
	 * Gets the activity billable.
	 *
	 * @return the activity billable
	 */
	@Column(name = "ACTIVITY_BILLABLE", nullable = false, length = 20)
	@Type(type="true_false")
	public Boolean getActivityBillable() {
		return this.activityBillable;
	}

	/**
	 * Sets the activity billable.
	 *
	 * @param activityBillable the new activity billable
	 */
	public void setActivityBillable(Boolean activityBillable) {
		this.activityBillable = activityBillable;
	}

	/**
	 * Gets the activity user.
	 *
	 * @return the activity user
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTIVITY_USER_ID")
	public ApnaUser getActivityUser() {
		return this.activityUser;
	}

	/**
	 * Sets the activity user.
	 *
	 * @param activityUser the new activity user
	 */
	public void setActivityUser(ApnaUser activityUser) {
		this.activityUser = activityUser;
	}

	/**
	 * Gets the sys modification timestamp.
	 *
	 * @return the sys modification timestamp
	 */
	@Column(name = "SYS_MODIFICATION_TIMESTAMP", nullable = false)
	public Timestamp getSysModificationTimestamp() {
		return this.sysModificationTimestamp;
	}

	/**
	 * Sets the sys modification timestamp.
	 *
	 * @param sysModificationTimestamp the new sys modification timestamp
	 */
	public void setSysModificationTimestamp(Timestamp sysModificationTimestamp) {
		this.sysModificationTimestamp = sysModificationTimestamp;
	}

	/**
	 * Gets the sys modification user.
	 *
	 * @return the sys modification user
	 */
	@Column(name = "SYS_MODIFICATION_USER", nullable = false)
	public ApnaUser getSysModificationUser() {
		return sysModificationUser;
	}
	
	public void setSysModificationUser(ApnaUser sysModificationUser) {
		this.sysModificationUser = sysModificationUser;
	}
}
