package hr.optimit.hibernate.model;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * UtPartner generated by hbm2java.
 */
@Entity
@Table(name = "UT_PARTNER")
public class UtPartner implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** The partner id. */
	private Long partnerId;
	
	/** The partner shortname. */
	private String partnerShortname;
	
	/** The partner name. */
	private String partnerName;
	
	/** The partner active. */
	private String partnerActive;
	
	/** The sys modification timestamp. */
	private Timestamp sysModificationTimestamp;
	
	/** The sys modification user. */
	private ApnaUser sysModificationUser;
	
	/** The ut projects. */
	private Set<UtProject> utProjects = new HashSet<UtProject>(0);
	
	/** The ut locations. */
	private Set<UtLocation> utLocations = new HashSet<UtLocation>(0);

	/**
	 * Instantiates a new ut partner.
	 */
	public UtPartner() {
	}

	/**
	 * Instantiates a new ut partner.
	 *
	 * @param partnerId the partner id
	 * @param partnerShortname the partner shortname
	 * @param partnerName the partner name
	 * @param partnerActive the partner active
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 */
	public UtPartner(Long partnerId, String partnerShortname, String partnerName, String partnerActive,
			Timestamp sysModificationTimestamp, ApnaUser sysModificationUser) {
		this.partnerId = partnerId;
		this.partnerShortname = partnerShortname;
		this.partnerName = partnerName;
		this.partnerActive = partnerActive;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
	}

	/**
	 * Instantiates a new ut partner.
	 *
	 * @param partnerId the partner id
	 * @param partnerShortname the partner shortname
	 * @param partnerName the partner name
	 * @param partnerActive the partner active
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 * @param utProjects the ut projects
	 * @param utLocations the ut locations
	 */
	public UtPartner(Long partnerId, String partnerShortname, String partnerName, String partnerActive,
			Timestamp sysModificationTimestamp, ApnaUser sysModificationUser, Set<UtProject> utProjects, Set<UtLocation> utLocations) {
		this.partnerId = partnerId;
		this.partnerShortname = partnerShortname;
		this.partnerName = partnerName;
		this.partnerActive = partnerActive;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
		this.utProjects = utProjects;
		this.utLocations = utLocations;
	}

	/**
	 * Gets the partner id.
	 *
	 * @return the partner id
	 */
	@Id
	@Column(name = "PARTNER_ID", unique = true, nullable = false)
	public Long getPartnerId() {
		return this.partnerId;
	}

	/**
	 * Sets the partner id.
	 *
	 * @param partnerId the new partner id
	 */
	public void setPartnerId(Long partnerId) {
		this.partnerId = partnerId;
	}

	/**
	 * Gets the partner shortname.
	 *
	 * @return the partner shortname
	 */
	@Column(name = "PARTNER_SHORTNAME", nullable = false, length = 20)
	public String getPartnerShortname() {
		return this.partnerShortname;
	}

	/**
	 * Sets the partner shortname.
	 *
	 * @param partnerShortname the new partner shortname
	 */
	public void setPartnerShortname(String partnerShortname) {
		this.partnerShortname = partnerShortname;
	}

	/**
	 * Gets the partner name.
	 *
	 * @return the partner name
	 */
	@Column(name = "PARTNER_NAME", nullable = false, length = 200)
	public String getPartnerName() {
		return this.partnerName;
	}

	/**
	 * Sets the partner name.
	 *
	 * @param partnerName the new partner name
	 */
	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	/**
	 * Gets the partner active.
	 *
	 * @return the partner active
	 */
	@Column(name = "PARTNER_ACTIVE", nullable = false, length = 10)
	public String getPartnerActive() {
		return this.partnerActive;
	}

	/**
	 * Sets the partner active.
	 *
	 * @param partnerActive the new partner active
	 */
	public void setPartnerActive(String partnerActive) {
		this.partnerActive = partnerActive;
	}

	/**
	 * Gets the sys modification timestamp.
	 *
	 * @return the sys modification timestamp
	 */
	@Column(name = "SYS_MODIFICATION_TIMESTAMP", nullable = false)
	public Timestamp getSysModificationTimestamp() {
		return this.sysModificationTimestamp;
	}

	/**
	 * Sets the sys modification timestamp.
	 *
	 * @param sysModificationTimestamp the new sys modification timestamp
	 */
	public void setSysModificationTimestamp(Timestamp sysModificationTimestamp) {
		this.sysModificationTimestamp = sysModificationTimestamp;
	}

	/**
	 * Gets the sys modification user.
	 *
	 * @return the sys modification user
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_MODIFICATION_USER", nullable = false)
	public ApnaUser getSysModificationUser() {
		return this.sysModificationUser;
	}

	/**
	 * Sets the sys modification user.
	 *
	 * @param sysModificationUser the new sys modification user
	 */
	public void setSysModificationUser(ApnaUser sysModificationUser) {
		this.sysModificationUser = sysModificationUser;
	}

	/**
	 * Gets the ut projects.
	 *
	 * @return the ut projects
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utPartner")
	public Set<UtProject> getUtProjects() {
		return this.utProjects;
	}

	/**
	 * Sets the ut projects.
	 *
	 * @param utProjects the new ut projects
	 */
	public void setUtProjects(Set<UtProject> utProjects) {
		this.utProjects = utProjects;
	}

	/**
	 * Gets the ut locations.
	 *
	 * @return the ut locations
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utPartner")
	public Set<UtLocation> getUtLocations() {
		return this.utLocations;
	}

	/**
	 * Sets the ut locations.
	 *
	 * @param utLocations the new ut locations
	 */
	public void setUtLocations(Set<UtLocation> utLocations) {
		this.utLocations = utLocations;
	}

}
