package hr.optimit.hibernate.model;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * UtUser2project generated by hbm2java.
 */
@Entity
@Table(name = "UT_USER2PROJECT")
public class UtUser2project implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/** The user2project id. */
	private Long user2projectId;
	
	/** The ut project. */
	private UtProject utProject;
	
	/** The user2project user id. */
	private Long user2projectUserId;
	
	/** The user2project priority. */
	private Long user2projectPriority;
	
	/** The sys modification timestamp. */
	private Timestamp sysModificationTimestamp;
	
	/** The sys modification user. */
	private ApnaUser sysModificationUser;

	/**
	 * Instantiates a new ut user2project.
	 */
	public UtUser2project() {
	}

	/**
	 * Instantiates a new ut user2project.
	 *
	 * @param user2projectId the user2project id
	 * @param utProject the ut project
	 * @param user2projectUserId the user2project user id
	 * @param user2projectPriority the user2project priority
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 */
	public UtUser2project(Long user2projectId, UtProject utProject, Long user2projectUserId,
			Long user2projectPriority, Timestamp sysModificationTimestamp, ApnaUser sysModificationUser) {
		this.user2projectId = user2projectId;
		this.utProject = utProject;
		this.user2projectUserId = user2projectUserId;
		this.user2projectPriority = user2projectPriority;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
	}

	/**
	 * Gets the user2project id.
	 *
	 * @return the user2project id
	 */
	@Id

	@Column(name = "USER2PROJECT_ID", unique = true, nullable = false)
	public Long getUser2projectId() {
		return this.user2projectId;
	}

	/**
	 * Sets the user2project id.
	 *
	 * @param user2projectId the new user2project id
	 */
	public void setUser2projectId(Long user2projectId) {
		this.user2projectId = user2projectId;
	}

	/**
	 * Gets the ut project.
	 *
	 * @return the ut project
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER2PROJECT_PROJECT_ID", nullable = false)
	public UtProject getUtProject() {
		return this.utProject;
	}

	/**
	 * Sets the ut project.
	 *
	 * @param utProject the new ut project
	 */
	public void setUtProject(UtProject utProject) {
		this.utProject = utProject;
	}

	/**
	 * Gets the user2project user id.
	 *
	 * @return the user2project user id
	 */
	@Column(name = "USER2PROJECT_USER_ID", nullable = false)
	public Long getUser2projectUserId() {
		return this.user2projectUserId;
	}

	/**
	 * Sets the user2project user id.
	 *
	 * @param user2projectUserId the new user2project user id
	 */
	public void setUser2projectUserId(Long user2projectUserId) {
		this.user2projectUserId = user2projectUserId;
	}

	/**
	 * Gets the user2project priority.
	 *
	 * @return the user2project priority
	 */
	@Column(name = "USER2PROJECT_PRIORITY", nullable = false)
	public Long getUser2projectPriority() {
		return this.user2projectPriority;
	}

	/**
	 * Sets the user2project priority.
	 *
	 * @param user2projectPriority the new user2project priority
	 */
	public void setUser2projectPriority(Long user2projectPriority) {
		this.user2projectPriority = user2projectPriority;
	}

	/**
	 * Gets the sys modification timestamp.
	 *
	 * @return the sys modification timestamp
	 */
	@Column(name = "SYS_MODIFICATION_TIMESTAMP", nullable = false)
	public Timestamp getSysModificationTimestamp() {
		return this.sysModificationTimestamp;
	}

	/**
	 * Sets the sys modification timestamp.
	 *
	 * @param sysModificationTimestamp the new sys modification timestamp
	 */
	public void setSysModificationTimestamp(Timestamp sysModificationTimestamp) {
		this.sysModificationTimestamp = sysModificationTimestamp;
	}

	/**
	 * Gets the sys modification user.
	 *
	 * @return the sys modification user
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_MODIFICATION_USER", nullable = false)
	public ApnaUser getSysModificationUser() {
		return this.sysModificationUser;
	}

	/**
	 * Sets the sys modification user.
	 *
	 * @param sysModificationUser the new sys modification user
	 */
	public void setSysModificationUser(ApnaUser sysModificationUser) {
		this.sysModificationUser = sysModificationUser;
	}

}
