package hr.optimit.hibernate.model;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * UtUser2task generated by hbm2java.
 */
@Entity
@Table(name = "UT_USER2TASK")
public class UtUser2task implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/** The user2task id. */
	private Long user2taskId;
	
	/** The ut task. */
	private UtTask utTask;
	
	/** The user2task user id. */
	private Long user2taskUserId;
	
	/** The user2task priority. */
	private Long user2taskPriority;
	
	/** The sys modification timestamp. */
	private Timestamp sysModificationTimestamp;
	
	/** The sys modification user. */
	private Long sysModificationUser;

	/**
	 * Instantiates a new ut user2task.
	 */
	public UtUser2task() {
	}

	/**
	 * Instantiates a new ut user2task.
	 *
	 * @param user2taskId the user2task id
	 * @param utTask the ut task
	 * @param user2taskUserId the user2task user id
	 * @param user2taskPriority the user2task priority
	 * @param sysModificationTimestamp the sys modification timestamp
	 * @param sysModificationUser the sys modification user
	 */
	public UtUser2task(Long user2taskId, UtTask utTask, Long user2taskUserId, Long user2taskPriority,
			Timestamp sysModificationTimestamp, Long sysModificationUser) {
		this.user2taskId = user2taskId;
		this.utTask = utTask;
		this.user2taskUserId = user2taskUserId;
		this.user2taskPriority = user2taskPriority;
		this.sysModificationTimestamp = sysModificationTimestamp;
		this.sysModificationUser = sysModificationUser;
	}

	/**
	 * Gets the user2task id.
	 *
	 * @return the user2task id
	 */
	@Id
	@Column(name = "USER2TASK_ID", unique = true, nullable = false)
	public Long getUser2taskId() {
		return this.user2taskId;
	}

	/**
	 * Sets the user2task id.
	 *
	 * @param user2taskId the new user2task id
	 */
	public void setUser2taskId(Long user2taskId) {
		this.user2taskId = user2taskId;
	}

	/**
	 * Gets the ut task.
	 *
	 * @return the ut task
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER2TASK_TASK_ID", nullable = false)
	public UtTask getUtTask() {
		return this.utTask;
	}

	/**
	 * Sets the ut task.
	 *
	 * @param utTask the new ut task
	 */
	public void setUtTask(UtTask utTask) {
		this.utTask = utTask;
	}

	/**
	 * Gets the user2task user id.
	 *
	 * @return the user2task user id
	 */
	@Column(name = "USER2TASK_USER_ID", nullable = false)
	public Long getUser2taskUserId() {
		return this.user2taskUserId;
	}

	/**
	 * Sets the user2task user id.
	 *
	 * @param user2taskUserId the new user2task user id
	 */
	public void setUser2taskUserId(Long user2taskUserId) {
		this.user2taskUserId = user2taskUserId;
	}

	/**
	 * Gets the user2task priority.
	 *
	 * @return the user2task priority
	 */
	@Column(name = "USER2TASK_PRIORITY", nullable = false)
	public Long getUser2taskPriority() {
		return this.user2taskPriority;
	}

	/**
	 * Sets the user2task priority.
	 *
	 * @param user2taskPriority the new user2task priority
	 */
	public void setUser2taskPriority(Long user2taskPriority) {
		this.user2taskPriority = user2taskPriority;
	}

	/**
	 * Gets the sys modification timestamp.
	 *
	 * @return the sys modification timestamp
	 */
	@Column(name = "SYS_MODIFICATION_TIMESTAMP", nullable = false)
	public Timestamp getSysModificationTimestamp() {
		return this.sysModificationTimestamp;
	}

	/**
	 * Sets the sys modification timestamp.
	 *
	 * @param sysModificationTimestamp the new sys modification timestamp
	 */
	public void setSysModificationTimestamp(Timestamp sysModificationTimestamp) {
		this.sysModificationTimestamp = sysModificationTimestamp;
	}

	/**
	 * Gets the sys modification user.
	 *
	 * @return the sys modification user
	 */
	@Column(name = "SYS_MODIFICATION_USER", nullable = false)
	public Long getSysModificationUser() {
		return this.sysModificationUser;
	}

	/**
	 * Sets the sys modification user.
	 *
	 * @param sysModificationUser the new sys modification user
	 */
	public void setSysModificationUser(Long sysModificationUser) {
		this.sysModificationUser = sysModificationUser;
	}

}
